<script src="<?= urlOf('assets/js/jquery-3.6.0.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/bootstrap/bootstrap.bundle.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/icons/feather-icon/feather.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/icons/feather-icon/feather-icon.js') ?>"></script>
<script src="<?= urlOf('assets/js/scrollbar/simplebar.js') ?>"></script>
<script src="<?= urlOf('assets/js/scrollbar/custom.js') ?>"></script>
<script src="<?= urlOf('assets/js/config.js') ?>"></script>
<script src="<?= urlOf('assets/js/sidebar-menu.js') ?>"></script>
<script src="<?= urlOf('assets/js/chart/chartist/chartist.js') ?>"></script>
<script src="<?= urlOf('assets/js/chart/chartist/chartist-plugin-tooltip.js') ?>"></script>
<script src="<?= urlOf('assets/js/chart/apex-chart/apex-chart.js') ?>"></script>
<script src="<?= urlOf('assets/js/chart/apex-chart/stock-prices.js') ?>"></script>
<script src="<?= urlOf('assets/js/prism/prism.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/clipboard/clipboard.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/custom-card/custom-card.js') ?>"></script>
<script src="<?= urlOf('assets/js/notify/bootstrap-notify.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/jquery-jvectormap-2.0.2.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-world-mill-en.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-us-aea-en.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-uk-mill-en.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-au-mill.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-chicago-mill-en.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-in-mill.js') ?>"></script>
<script src="<?= urlOf('assets/js/vector-map/map/jquery-jvectormap-asia-mill.js') ?>"></script>
<script src="<?= urlOf('assets/js/dashboard/default.js') ?>"></script>
<script src="<?= urlOf('assets/js/notify/index.js') ?>"></script>
<script src="<?= urlOf('assets/js/typeahead/handlebars.js') ?>"></script>
<script src="<?= urlOf('assets/js/typeahead/typeahead.bundle.js') ?>"></script>
<script src="<?= urlOf('assets/js/typeahead/typeahead.custom.js') ?>"></script>
<script src="<?= urlOf('assets/js/typeahead-search/handlebars.js') ?>"></script>
<script src="<?= urlOf('assets/js/typeahead-search/typeahead-custom.js') ?>"></script>
<script src="<?= urlOf('assets/js/script.js">') ?>"></script>
<script src="<?= urlOf('assets/js/theme-customizer/customizer.js') ?>"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="<?= urlOf('assets/js/datatable/datatables/jquery.dataTables.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/datatable/datatables/datatable.custom.js') ?>"></script>
<script src="<?= urlOf('assets/js/tooltip-init.js') ?>"></script>